import Head from "next/head";

//Web3
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";

//components
import Profile from "./Profile";
import NavMenu from "./NavMenu";

//Styles - Default Style to Wallet Connection button
require("@solana/wallet-adapter-react-ui/styles.css");
import styles from "./Header.module.scss";
//Hoocks
import { useProfile } from "@/hooks/useProfile";
import { useProgramState } from "@/hooks/useProgram";

const image =
  "https://scontent-qro1-2.xx.fbcdn.net/v/t39.30808-6/339736635_1417065962458765_7019775077283824177_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=0debeb&_nc_eui2=AeH7RL2bHtgS4KFh-IDWo18KhmHk2uTfvpeGYeTa5N--l1ar8-HuYbh0T11yPgwXg2KQiiQQivzJ7g_Ewv0djQu_&_nc_ohc=E47koFW36aMAX-mglJ0&_nc_ht=scontent-qro1-2.xx&oh=00_AfCiKfnUo1Ra90pSkqIVSJl02y9EQfOrgkgVgp9xk9hAqw&oe=643F0E85";

export default function Header(props) {
  const { userRealAccountBalance } = props;
  const { connected, publicKey, avatar, setAvatar, userAddress } = useProfile();
  const { isConnected, hasUserAccount, createUser } = useProgramState();

  const title = "UPIITA TTT-2022/2-14";

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by Dream Team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <Profile avatar={avatar} userAddress={userAddress} image={image} />
        <WalletMultiButton></WalletMultiButton>

        <NavMenu userRealAccountBalance={userRealAccountBalance} />
      </div>
    </>
  );
}
